### ISSUE TITLE
UnboundLocalError: local variable 'interval' referenced before assignment

### ISSUE THREAD

**Issue by J9DM** [YeoLab/rbp-maps#11]
I was able to install rbp-maps using Docker using the command `docker pull brianyee/rbp-maps:a5c9bd9` (but not `docker pull brianyee/rbp-maps`). However, I was not able to successfully run `plot_map` using either `--ipbam` for plotting density or `--peak` for plotting peaks.

For HPC, I need to use singularity, and this was one of my calls:
`singularity run rbpmaps.sif plot_map --peak <path_to_bigbed> --annotations <path_to_SE.MATS.JC.nonoverlap.txt> <path_to_HepG2_native_cassette_exons_all> --annotation_type rmats rmats --output <path_to_png> --event se --normalization_level 0 --testnums 0 --bgnum 1 --sigtest fisher
`

I received the following message:
Traceback (most recent call last):
  File "/opt/conda/bin/plot_map", line 11, in <module>
    load_entry_point('rbp-maps==0.1.4', 'console_scripts', 'plot_map')()
  File "/opt/conda/lib/python2.7/site-packages/rbp_maps-0.1.4-py2.7.egg/maps/plot_map.py", line 548, in main
  File "/opt/conda/lib/python2.7/site-packages/rbp_maps-0.1.4-py2.7.egg/maps/plot_map.py", line 104, in run_make_peak
  File "/opt/conda/lib/python2.7/site-packages/rbp_maps-0.1.4-py2.7.egg/density/Map.py", line 701, in create_matrices
  File "/opt/conda/lib/python2.7/site-packages/rbp_maps-0.1.4-py2.7.egg/density/matrix.py", line 562, in skipped_exon
UnboundLocalError: local variable 'interval' referenced before assignment

**Comment by byee4** [comment]
`singularity run rbpmaps.sif plot_map --peak <path_to_bigbed> --annotations <path_to_SE.MATS.JC.nonoverlap.txt> <path_to_HepG2_native_cassette_exons_all> --annotation_type rmats rmats --output <path_to_png> --event se --normalization_level 0 --testnums 0 --bgnum 1 --sigtest fisher`

Assuming <path_to_HepG2_native_cassette_exons_all> is one of the files downloaded from [here](https://external-collaborator-data.s3-us-west-1.amazonaws.com/reference-data/se-background-controls.tar.gz), could you try to see if this command runs? In other words, replace the second 'rmats' with 'tab' since the background control files were not generated with rMATS:

`singularity run rbpmaps.sif plot_map --peak <path_to_bigbed> --annotations <path_to_SE.MATS.JC.nonoverlap.txt> <path_to_HepG2_native_cassette_exons_all> --annotation_type rmats tab --output <path_to_png> --event se --normalization_level 0 --testnums 0 --bgnum 1 --sigtest fisher`
