### ISSUE TITLE
plot_map fails if bam files are not indexed

### ISSUE THREAD

**Issue by ecwheele** [YeoLab/rbp-maps#7]
```Traceback (most recent call last):
  File "/home/ecwheele/anaconda2/bin/plot_map", line 11, in <module>
    load_entry_point('rbp-maps==0.1.4', 'console_scripts', 'plot_map')()
  File "build/bdist.linux-x86_64/egg/maps/plot_map.py", line 573, in main
  File "build/bdist.linux-x86_64/egg/maps/plot_map.py", line 301, in check_for_index
NameError: global name 'call' is not defined```

**Comment by byee4** [comment]
This happens when a bam file is used without its index, indexing the bam file will work around this bug for now.

**Comment by byee4** [comment]
Fixed.
